server:
    port: 11112
    max-http-header-size: 32KB


spring:
    main:
        allow-bean-definition-overriding: true

mybatis:
    type-aliases-package: com.xams.example.oauth2
    configuration:
        map-underscore-to-camel-case: true

logging:
    level:
        com.xams: debug

