spring:
    datasource:
        url: jdbc:mysql://${DEFAULT_HOST:localhost}:3306/skeleton_example_oauth2?createDatabaseIfNotExist=true&useSSL=false&useTimezone=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&characterEncoding=UTF-8
        hikari:
            validation-timeout: 30000
            connection-timeout: 200000
            connection-test-query: SELECT 1
            minimum-idle: 2
            maximum-pool-size: 4
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}

    redis:
        key-prefix: 'xams:user-center:'
        database: 1
        port: 6379
        timeout: 20000
        host: ${DEFAULT_HOST}
        password: ${MYSQL_PASSWORD}
